replicaCount: 1
image:
  repository: gcr.io/kubernetescluster-265514/gps-tracker
  tag: "snapshot"

ADMIN_TOKEN: "zubale"
DATABASE_URL: "postgres://edbngdcthxzupt:p2bca442050386c13a85178cd56fbac3a5529bebebe44d942a42c33286fb7ca8f@gps-tracker-db-postgresql.database.svc.cluster.local:5432/dfsrmj16kaod5h"
GOOGLE_MAPS_API_KEY: "AIzaSyDaeHT-h8lqzMRcEkGrr7Gu73cmMBYYL78"
NODE_TLS_REJECT_UNAUTHORIZED: "0"
NPM_CONFIG_PRODUCTION: "false"
PASSWORD: "12345678"
SHARED_DASHBOARD: "1"



